# Generated by Django 4.1.3 on 2022-11-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='casemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseid', models.CharField(max_length=200, null=True)),
                ('casename', models.CharField(max_length=200, null=True)),
                ('discription', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('vehicleno', models.CharField(max_length=200, null=True)),
                ('vehicleownername', models.CharField(max_length=200, null=True)),
                ('vehicleownerid', models.CharField(max_length=200, null=True)),
                ('amount', models.CharField(max_length=200, null=True)),
                ('date', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='regmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('phoneNumber', models.CharField(max_length=200, null=True)),
                ('adrs', models.CharField(max_length=200, null=True)),
                ('District', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
