# Generated by Django 4.1.3 on 2022-11-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficapp', '0002_rulemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='usermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('upassword', models.CharField(max_length=200, null=True)),
                ('phoneNumber', models.CharField(max_length=200, null=True)),
                ('adrs', models.CharField(max_length=200, null=True)),
                ('District', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
