# Generated by Django 4.1.1 on 2022-11-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficapp', '0003_usermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='vehicleownerid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
