# Generated by Django 4.1.1 on 2022-11-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficapp', '0004_usermodel_vehicleownerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='resultmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleownerid', models.CharField(max_length=200, null=True)),
                ('uname', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
