# Generated by Django 4.1.1 on 2022-11-07 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trafficapp', '0005_resultmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='vehicleownerid',
            new_name='vid',
        ),
    ]
