# Generated by Django 4.1.1 on 2022-11-07 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trafficapp', '0006_rename_vehicleownerid_usermodel_vid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='vid',
            new_name='vehicleownerid',
        ),
    ]
