# Generated by Django 4.1.1 on 2022-11-07 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trafficapp', '0007_rename_vid_usermodel_vehicleownerid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='resultmodel',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='vehicleownerid',
            new_name='vid',
        ),
    ]
