# Generated by Django 4.1.1 on 2022-11-07 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trafficapp', '0008_delete_resultmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casemodel',
            old_name='vehicleownername',
            new_name='uname',
        ),
    ]
