# Generated by Django 4.1.1 on 2022-11-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficapp', '0009_rename_vehicleownername_casemodel_uname'),
    ]

    operations = [
        migrations.CreateModel(
            name='resultmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleno', models.CharField(max_length=200, null=True)),
                ('uname', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
