# Generated by Django 4.1.1 on 2022-11-07 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trafficapp', '0010_resultmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='resultmodel',
        ),
    ]
